# Generated by Django 6.0.1 on 2026-01-28 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_tag_book_book_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_tag',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='tags', to='books.book'),
        ),
    ]
