# Generated by Django 6.0.1 on 2026-01-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_book_tag_book_tag_tag_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, to='books.tag'),
        ),
    ]
